### ISSUE TITLE
Q un peu violent

### ISSUE THREAD

**Issue by lelfeSylvain** [chaissac/Tetris#1]
Salut,
Quand tu appuies sur Q, tu quittes la partie, sans confirmation en milieu de partie. C'est dommage quand tu te trompes de touche (le Q est au dessus du W...). 
La touche flèche haute pour descendre, c'est pas super naturel non plus ;)
Sinon, bravo , c'est chouette !

**Comment by chaissac** [comment]
Ouais c'est vrai que la touche Q est trop violente... Je vais la changer et ajouter une confirmation. 
Pour la touche flèche haut, je suis d'accord avec toi, j'avais dû trouver ce mapping dans un wiki. En premier jet, je n'avais que le soft-drop sur la touche flèche bas et pas de hard drop. La touche flèche haut faisait une rotation, et on ne pouvait tourner que dans un sens. Je crois que je vais faire un truc comme ça : https://tetris.com/play-tetris-content/resources/images/controls_and_scoring.png

**Comment by chaissac** [comment]
Voilà j'ai réaffecté les touches. Maintenant on quitte avec Q depuis la pause. Et le hard drop, c'est espace. 
J'ai aussi ajouté un Ghost (désactivable par 'G') et un effet 3D sur les briques grâce à un seul petit png et tint(), c'est magique ! J'adore Processing :)
